# Generated by Django 5.0.7 on 2024-08-13 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('E', 'ENTRADA'), ('S', 'SAIDA')], max_length=1)),
                ('valor_planejamento', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('banco', models.CharField(choices=[('NU', 'NuBank'), ('CE', 'Caixa Econômica'), ('MP', 'Mercado Pago')], max_length=2)),
                ('tipo', models.CharField(choices=[('pf', 'Pessoa Física'), ('pj', 'Pesssoa Jurídica')], max_length=2)),
                ('valor', models.FloatField(blank=True, null=True)),
                ('icone', models.ImageField(upload_to='icones')),
            ],
        ),
    ]
