# Generated by Django 5.0.7 on 2024-08-13 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='tipo',
            field=models.CharField(choices=[('E', 'ENTRADA'), ('S', 'SAIDA'), ('M', 'MENSAL')], max_length=1),
        ),
    ]
