# Generated by Django 5.0.7 on 2024-07-29 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('banco', models.CharField(choices=[('NU', 'NuBank'), ('CE', 'Caixa Econômica')], max_length=2)),
                ('tipo', models.CharField(choices=[('pf', 'Pessoa Física'), ('pj', 'Pesssoa Jurídica')], max_length=2)),
                ('valor', models.FloatField()),
                ('icone', models.ImageField(upload_to='icones')),
            ],
        ),
    ]
