# Generated by Django 5.0.7 on 2024-08-01 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0002_conta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conta',
            name='banco',
            field=models.CharField(choices=[('NU', 'NuBank'), ('CE', 'Caixa Econômica'), ('MP', 'Mercado Pago')], max_length=2),
        ),
    ]
