# Generated by Django 5.0.7 on 2024-08-13 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contapaga',
            old_name='dia_pagamento',
            new_name='pago_dia',
        ),
    ]
