# Generated by Django 5.0.7 on 2024-08-15 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0001_initial'),
        ('perfil', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transferencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('data', models.DateField()),
                ('conta_destino', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='transferencias_destino', to='perfil.conta')),
                ('conta_partida', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='transferencias_partida', to='perfil.conta')),
            ],
            options={
                'verbose_name': 'Transferências',
                'verbose_name_plural': 'Transferências',
            },
        ),
    ]
