# Generated by Django 5.0.7 on 2024-08-10 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0002_contapagar_contapaga'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contapagar',
            old_name='data_pagamento',
            new_name='dia_pagamento',
        ),
    ]
