# Generated by Django 5.0.7 on 2024-08-12 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0002_alter_contapagar_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='contapaga',
            name='valor',
            field=models.FloatField(default=0),
        ),
    ]
