# Generated by Django 5.0.7 on 2024-08-13 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0002_rename_dia_pagamento_contapaga_pago_dia'),
        ('perfil', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contapagar',
            name='categoria',
        ),
        migrations.CreateModel(
            name='ContasMensais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('valor', models.FloatField(blank=True, null=True)),
                ('dia_vencimento', models.DateField()),
                ('conta_paga', models.BooleanField(default=False)),
                ('pago_dia', models.DateField(blank=True, null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='perfil.categoria')),
                ('conta_pagamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='perfil.conta')),
            ],
            options={
                'verbose_name': 'Contas Mensais',
                'verbose_name_plural': 'Contas Mensais',
            },
        ),
        migrations.DeleteModel(
            name='ContaPaga',
        ),
        migrations.DeleteModel(
            name='ContaPagar',
        ),
    ]
