# Generated by Django 5.0.7 on 2024-08-11 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0003_rename_data_pagamento_contapagar_dia_pagamento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contapaga',
            options={'verbose_name': 'Contas Pagas', 'verbose_name_plural': 'Contas Pagas'},
        ),
        migrations.AlterModelOptions(
            name='contapagar',
            options={'verbose_name': 'Contas a Pagar', 'verbose_name_plural': 'Contas a Pagar'},
        ),
        migrations.AlterModelOptions(
            name='movimentacao',
            options={'verbose_name': 'Movimentação da conta', 'verbose_name_plural': 'Movimentação da conta'},
        ),
        migrations.AlterField(
            model_name='contapagar',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
