# Generated by Django 5.0.7 on 2024-08-11 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0004_alter_contapaga_options_alter_contapagar_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contapaga',
            old_name='data_pagamento',
            new_name='dia_pagamento',
        ),
    ]
